/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    MdiClockOutline: typeof import('~icons/mdi/clock-outline')['default']
    MdiFileOutline: typeof import('~icons/mdi/file-outline')['default']
    MdiMapMarkerOutline: typeof import('~icons/mdi/map-marker-outline')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
