version: "2.1"
services: 
  nocodb: 
    depends_on: 
      root_db: 
        condition: service_healthy
    environment: 
      NC_DB: "mysql2://noco_dev_db:3306?u=noco&p=password&d=noco_dev_db"
    image: "phuocnt3110/xerp:lastest"
    ports: 
<<<<<<< HEAD
      - "8082:8082"
=======
<<<<<<< HEAD
      - "3333:3333"
=======
      - "8088:8088"
>>>>>>> ae915c88fe6b4c509747925bbd1f2478becdc775
>>>>>>> 9a013974e5f30d0c52374f5ca4afc76ec671dbe3
    restart: always
    volumes: 
      - "nc_data:/usr/app/data"
  root_db: 
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: noco_dev_db
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: noco
    healthcheck: 
      retries: 10
      test: 
        - CMD
        - mysqladmin
        - ping
        - "-h"
        - localhost
      timeout: 20s
    image: "mysql:8.3.0"
    restart: always
    volumes: 
      - "db_data:/var/lib/mysql"
#    below line shows how to change charset and collation
#    uncomment it if necessary
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
volumes: 
  db_data: {}
  nc_data: {}

# docker run -d -p 3306:3306 -v /root/nc-db-mysql:/var/lib/mysql -e MYSQL_DATABASE=root_db -e MYSQL_PASSWORD=password -e MYSQL_ROOT_PASSWORD=password -e MYSQL_USER=noco --name nocodb-mysql mysql:latest
# docker run -p 8080:8080 -e NC_DB="mysql2://host.docker.internal:3306?u=noco&p=password&d=dev_db" --add-host=host.docker.internal:host-gateway --name nocodb-prod nocodb/nocodb

